"""Launcher for Fig4b render export.

This is a lightweight launcher for submission packaging:
- load existing PNG from v2_subplots/final paper-facing assets
- export 800 DPI PNG
- copy native SVG/PDF sidecars generated by the original plotting script

Raster-embedded SVG fallback is intentionally forbidden because it cannot be
edited reliably in Adobe Illustrator.
"""

from __future__ import annotations

from pathlib import Path

try:
    from PIL import Image
except Exception:
    Image = None


def locate_repo_root() -> Path:
    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "analysis_viz").exists():
            return parent
    return current.parents[-1]


ROOT = locate_repo_root()
SRC_PNG = ROOT / "analysis_viz/figures/v2_subplots/G3_continuity/G3B_consistency_trend_v2.png"


def copy_required_sidecar(suffix: str, render_dir: Path) -> Path:
    native_path = SRC_PNG.with_suffix(suffix)
    if not native_path.exists():
        raise FileNotFoundError(
            f"Missing native vector sidecar: {native_path}. "
            "Do not create raster-embedded SVG; re-run build_v2_subplots_bundle.py."
        )
    out_path = render_dir / f"Fig4b{suffix}"
    out_path.write_bytes(native_path.read_bytes())
    return out_path


def main() -> None:
    render_dir = Path(__file__).resolve().parents[1] / "render"
    render_dir.mkdir(parents=True, exist_ok=True)
    out_png = render_dir / "Fig4b.png"

    if Image is not None:
        try:
            with Image.open(SRC_PNG) as img:
                img.save(out_png, dpi=(800, 800))
        except Exception:
            out_png.write_bytes(SRC_PNG.read_bytes())
    else:
        out_png.write_bytes(SRC_PNG.read_bytes())

    out_svg = copy_required_sidecar(".svg", render_dir)
    out_pdf = copy_required_sidecar(".pdf", render_dir)

    print("DONE", out_png, out_svg, out_pdf)


if __name__ == "__main__":
    main()
