"""Build analysis_viz registries.

This script is intentionally lightweight and repo-local:
- No external services.
- Only scans files under analysis_viz/.

Outputs:
- analysis_viz/docs/figure_registry.csv

Note: deeper metric/figure curation is tracked separately in docs/*.csv.
"""

from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
ANALYSIS_VIZ = ROOT / "analysis_viz"

PAPER_FIG_DIR = ANALYSIS_VIZ / "figures" / "paper"
VARIANT_DIR = ANALYSIS_VIZ / "figures" / "variants"

PAPER_FIGDATA_DIR = ANALYSIS_VIZ / "data" / "derived" / "figdata" / "paper"
ARCHIVE_FIGDATA_SOURCE_DIR = (
    ANALYSIS_VIZ / "data" / "derived" / "figdata" / "archive_2026-02-06" / "source_data"
)

FIGURE_REGISTRY = ANALYSIS_VIZ / "docs" / "figure_registry.csv"


FIGURE_ID_RE = re.compile(r"^(Fig\d+[A-Za-z]?)")


@dataclass(frozen=True)
class FigureRow:
    figure_id: str
    figure_file: str
    figure_relpath: str
    figure_source: str
    derived_detail_relpath: str
    derived_summary_relpath: str
    source_data_relpath: str
    raw_source_relpath: str
    script_path: str
    script_entry: str
    script_status: str
    used_in_paper: str
    variant_group: str
    notes: str


def _rel(p: Path) -> str:
    try:
        return str(p.relative_to(ROOT)).replace("\\", "/")
    except ValueError:
        return str(p).replace("\\", "/")


def _guess_group_prefix(fig_id: str) -> str:
    """Map Fig2a -> Fig2, Fig11A -> Fig11; else return itself."""
    if re.match(r"^Fig\d+[A-Za-z]$", fig_id):
        return fig_id[:-1]
    return fig_id


def _paper_figdata_candidates(fig_id: str) -> list[Path]:
    if not PAPER_FIGDATA_DIR.exists():
        return []
    prefixes = [fig_id, _guess_group_prefix(fig_id)]
    seen: set[Path] = set()
    out: list[Path] = []
    for prefix in prefixes:
        for p in sorted(PAPER_FIGDATA_DIR.glob(f"{prefix}__*")):
            if p in seen:
                continue
            seen.add(p)
            out.append(p)
    return out


def _write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def build_figure_registry() -> None:
    rows: list[dict[str, str]] = []

    # 1) Paper figures
    if PAPER_FIG_DIR.exists():
        for fig_path in sorted(PAPER_FIG_DIR.glob("Fig*.png")):
            m = FIGURE_ID_RE.match(fig_path.name)
            fig_id = m.group(1) if m else fig_path.stem.split("_", 1)[0]
            figdata_files = _paper_figdata_candidates(fig_id)
            figdata_rel = "|".join(_rel(p) for p in figdata_files)

            rows.append(
                FigureRow(
                    figure_id=fig_id,
                    figure_file=fig_path.name,
                    figure_relpath=_rel(fig_path),
                    figure_source="paper",
                    derived_detail_relpath="",
                    derived_summary_relpath="",
                    source_data_relpath=figdata_rel,
                    raw_source_relpath="",
                    script_path="scripts/prepare_paper_figures.py",
                    script_entry="copy_figures()",
                    script_status="found",
                    used_in_paper="yes",
                    variant_group=fig_id,
                    notes="paper figdata listed in source_data_relpath" if figdata_rel else "no matched figdata prefix",
                ).__dict__
            )

    # 2) Variants (outputs_latest + archive)
    if VARIANT_DIR.exists():
        for png_path in sorted(VARIANT_DIR.rglob("*.png")):
            rel = _rel(png_path)

            fig_source = "variants"
            if "outputs_latest__" in rel:
                fig_source = "outputs_latest"
            if "archive_2026-02-06__" in rel:
                fig_source = "archive_2026-02-06"

            used = "variant"
            if "outputs_latest__llm" in rel:
                used = "no"
            if "/consistency/" in rel:
                used = "no"

            script_path = ""
            script_entry = ""
            script_status = "unknown"

            # Most variants are generated by the stagewise figure generator.
            if fig_source in {"outputs_latest", "archive_2026-02-06"}:
                script_path = "src/tools/generate_figures_chunked.py"
                run_id = "latest" if fig_source == "outputs_latest" else "archive/2026-02-06_05-24-36_latest"
                part = "all"
                if "outputs_latest__algorithmic" in rel or "archive_2026-02-06__algorithmic" in rel:
                    part = "algorithmic"
                elif "outputs_latest__alignment" in rel or "archive_2026-02-06__alignment" in rel:
                    part = "alignment"
                elif "outputs_latest__calibration" in rel:
                    part = "calibration"
                elif "outputs_latest__sankey" in rel:
                    part = "sankey"
                elif "outputs_latest__special" in rel:
                    part = "special"
                script_entry = f"python src/tools/generate_figures_chunked.py --run_id {run_id} --part {part}"
                script_status = "found"

            # attempt to find matching source_data xlsx next to png
            source_data = ""
            if png_path.parent.name != "source_data":
                candidate_dir = png_path.parent / "source_data"
                if candidate_dir.exists():
                    xlsx = candidate_dir / f"{png_path.stem}_source.xlsx"
                    if xlsx.exists():
                        source_data = _rel(xlsx)

            # archive variants: source_data is stored centrally to avoid duplication
            if not source_data and fig_source == "archive_2026-02-06" and ARCHIVE_FIGDATA_SOURCE_DIR.exists():
                xlsx = ARCHIVE_FIGDATA_SOURCE_DIR / f"{png_path.stem}_source.xlsx"
                if xlsx.exists():
                    source_data = _rel(xlsx)

            rows.append(
                FigureRow(
                    figure_id=png_path.stem,
                    figure_file=png_path.name,
                    figure_relpath=rel,
                    figure_source=fig_source,
                    derived_detail_relpath="",
                    derived_summary_relpath="",
                    source_data_relpath=source_data,
                    raw_source_relpath="",
                    script_path=script_path,
                    script_entry=script_entry,
                    script_status=script_status,
                    used_in_paper=used,
                    variant_group=png_path.parent.name,
                    notes="",
                ).__dict__
            )

    fieldnames = [
        "figure_id",
        "figure_file",
        "figure_relpath",
        "figure_source",
        "derived_detail_relpath",
        "derived_summary_relpath",
        "source_data_relpath",
        "raw_source_relpath",
        "script_path",
        "script_entry",
        "script_status",
        "used_in_paper",
        "variant_group",
        "notes",
    ]
    _write_csv(FIGURE_REGISTRY, fieldnames, rows)


def main() -> None:
    build_figure_registry()


if __name__ == "__main__":
    main()
